'From Cuis7.8 [latest update: #7977] on 24 September 2026 at 11:24:04 am'!
!classDefinition: #Causa category: #Kernel!
Object subclass: #Causa
	instanceVariableNames: 'nroExp fechaInicio juzgado fuero demandante demandado detalle nombreAbogado fechaCierre sentenciaF monto'
	classVariableNames: 'UltimoId'
	poolDictionaries: ''
	category: 'Kernel'!

!Causa methodsFor: 'as yet unclassified' stamp: 'lucio 17/Sep/2026 10:12:40'!
esAbierta! !

!Causa methodsFor: 'as yet unclassified' stamp: 'lc 24/Sep/2026 11:18:08'!
inicializarCausa! !

!Causa methodsFor: 'as yet unclassified' stamp: 'lucio 17/Sep/2026 10:12:04'!
registrarCierre! !
